import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Stairtransition from "@/components/Stairtransition";
import PageTransition from "@/components/PageTransition";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.variable}>
        <Header />
        <PageTransition>{children}</PageTransition>
        <Stairtransition />
      </body>
    </html>
  );
}
